name: "Terraform Executa Modulo"

on:
  push:
    branches:
      - main
  
jobs:
  terraform:
    uses: kelvinshammai/cicd_centralizado/.github/workflows/terraform_executa_modulo_aws.yaml@main
    with:
      run_apply: true
      run_plan: true
      tf_workspace: "default"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
