name: "Terraform Executa Modulo"

on:
  push:
    branches:
      - main
  
jobs:
  terraform:
    uses: "kelvinshammai/cicd_centralizado/.github/workflows/terraform_centralizado.yml@feat/unifica-pipelines-terraform"
    with:
      run_apply: true
      run_plan: true
      tf_workspace: "default"
